baseurl = "https://rojkov.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "Dmitry Rozhkov"
theme = "material"
disqusShortname = "idempotent"
paginate = 7

enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "github"
copyright = "© 2018 Dmitry Rozhkov"

