baseurl = "https://rojkov.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "Dmitry Rozhkov"
theme = "bilberry"
#disqusShortname = "idempotent"
paginate = 7

enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "github"
copyright = "© 2019 Dmitry Rozhkov"

# English
[languages.en]
  languageName = "English"

# Русский
[languages.ru]
  languageName = "Русский"
  title = "Дмитрий Рожков"
  copyright = "© 2019 Дмитрий Рожков"
