baseurl = "https://rojkov.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "Dmitry&nbsp;Rozhkov"
theme = "material"
disqusShortname = "idempotent"
paginate = 7

enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsStyle = "github"
copyright = "© 2018 Dmitry Rozhkov"

# English
[languages.en]
  languageName = "English"

# Русский
[languages.ru]
  languageName = "Русский"
  title = "Дмитрий&nbsp;Рожков"
  copyright = "© 2018 Дмитрий Рожков"
